/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as appRouteRouteImport } from './../routes/(app)/route'
import { Route as appIndexRouteImport } from './../routes/(app)/index'
import { Route as authLoginRouteImport } from './../routes/(auth)/login'
import { Route as appTripsRouteImport } from './../routes/(app)/trips'
import { Route as appTripRecordRouteImport } from './../routes/(app)/trip-record'
import { Route as appTripDetailRouteImport } from './../routes/(app)/trip-detail'
import { Route as appSettingsRouteImport } from './../routes/(app)/settings'
import { Route as appRoutesRouteImport } from './../routes/(app)/routes'
import { Route as appReportRouteImport } from './../routes/(app)/report'
import { Route as appPathsRouteImport } from './../routes/(app)/paths'
import { Route as appReportsAutomatedRouteImport } from './../routes/(app)/reports/automated'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appTripsRoute = appTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => appRouteRoute,
} as any)
const appTripRecordRoute = appTripRecordRouteImport.update({
  id: '/trip-record',
  path: '/trip-record',
  getParentRoute: () => appRouteRoute,
} as any)
const appTripDetailRoute = appTripDetailRouteImport.update({
  id: '/trip-detail',
  path: '/trip-detail',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appRoutesRoute = appRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportRoute = appReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => appRouteRoute,
} as any)
const appPathsRoute = appPathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportsAutomatedRoute = appReportsAutomatedRouteImport.update({
  id: '/reports/automated',
  path: '/reports/automated',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/paths': typeof appPathsRoute
  '/report': typeof appReportRoute
  '/routes': typeof appRoutesRoute
  '/settings': typeof appSettingsRoute
  '/trip-detail': typeof appTripDetailRoute
  '/trip-record': typeof appTripRecordRoute
  '/trips': typeof appTripsRoute
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/reports/automated': typeof appReportsAutomatedRoute
}
export interface FileRoutesByTo {
  '/paths': typeof appPathsRoute
  '/report': typeof appReportRoute
  '/routes': typeof appRoutesRoute
  '/settings': typeof appSettingsRoute
  '/trip-detail': typeof appTripDetailRoute
  '/trip-record': typeof appTripRecordRoute
  '/trips': typeof appTripsRoute
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/reports/automated': typeof appReportsAutomatedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/paths': typeof appPathsRoute
  '/(app)/report': typeof appReportRoute
  '/(app)/routes': typeof appRoutesRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(app)/trip-detail': typeof appTripDetailRoute
  '/(app)/trip-record': typeof appTripRecordRoute
  '/(app)/trips': typeof appTripsRoute
  '/(auth)/login': typeof authLoginRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/reports/automated': typeof appReportsAutomatedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/paths'
    | '/report'
    | '/routes'
    | '/settings'
    | '/trip-detail'
    | '/trip-record'
    | '/trips'
    | '/login'
    | '/'
    | '/reports/automated'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/paths'
    | '/report'
    | '/routes'
    | '/settings'
    | '/trip-detail'
    | '/trip-record'
    | '/trips'
    | '/login'
    | '/'
    | '/reports/automated'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/paths'
    | '/(app)/report'
    | '/(app)/routes'
    | '/(app)/settings'
    | '/(app)/trip-detail'
    | '/(app)/trip-record'
    | '/(app)/trips'
    | '/(auth)/login'
    | '/(app)/'
    | '/(app)/reports/automated'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/trips': {
      id: '/(app)/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof appTripsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/trip-record': {
      id: '/(app)/trip-record'
      path: '/trip-record'
      fullPath: '/trip-record'
      preLoaderRoute: typeof appTripRecordRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/trip-detail': {
      id: '/(app)/trip-detail'
      path: '/trip-detail'
      fullPath: '/trip-detail'
      preLoaderRoute: typeof appTripDetailRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/routes': {
      id: '/(app)/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof appRoutesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/report': {
      id: '/(app)/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof appReportRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/paths': {
      id: '/(app)/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof appPathsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/reports/automated': {
      id: '/(app)/reports/automated'
      path: '/reports/automated'
      fullPath: '/reports/automated'
      preLoaderRoute: typeof appReportsAutomatedRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appPathsRoute: typeof appPathsRoute
  appReportRoute: typeof appReportRoute
  appRoutesRoute: typeof appRoutesRoute
  appSettingsRoute: typeof appSettingsRoute
  appTripDetailRoute: typeof appTripDetailRoute
  appTripRecordRoute: typeof appTripRecordRoute
  appTripsRoute: typeof appTripsRoute
  appIndexRoute: typeof appIndexRoute
  appReportsAutomatedRoute: typeof appReportsAutomatedRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appPathsRoute: appPathsRoute,
  appReportRoute: appReportRoute,
  appRoutesRoute: appRoutesRoute,
  appSettingsRoute: appSettingsRoute,
  appTripDetailRoute: appTripDetailRoute,
  appTripRecordRoute: appTripRecordRoute,
  appTripsRoute: appTripsRoute,
  appIndexRoute: appIndexRoute,
  appReportsAutomatedRoute: appReportsAutomatedRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
